name: Baselines

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: baselines

jobs:
  test_baselines:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12
      - name: Install build tools
        run: |
          python -m pip install -U pip==22.0.4
          python -m pip install -U setuptools==60.9.3
          python -m pip install -U poetry==1.1.13
          poetry config virtualenvs.create false
      - name: Install dependencies
        run: |
          python -m poetry install
      - name: Lint + Test (isort/black/mypy/pylint/pytest)
        run: ./dev/test.sh
