name: Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build docs
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.12
      - name: Install build tools
        run: |
          python -m pip install -U pip==22.0.4
          python -m pip install -U setuptools==60.9.3
          python -m pip install -U poetry==1.1.13
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory only)
        run: python -m poetry install --extras "simulation"
      - name: Build and deploy docs
        env:
          AWS_DEFAULT_REGION: ${{ secrets. AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
        run: ./dev/build-docs.sh

  deploy_docs:
    needs: build_docs
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy docs
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.12
      - name: Install build tools
        run: |
          python -m pip install -U pip==22.0.4
          python -m pip install -U setuptools==60.9.3
          python -m pip install -U poetry==1.1.13
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory only)
        run: python -m poetry install --extras "simulation"
      - name: Build and deploy docs
        env:
          AWS_DEFAULT_REGION: ${{ secrets. AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
        run: ./dev/deploy-docs.sh
